---
ruby_version: "3.3.0"
rails_env: "{{ environment }}"
app_user: deploy
app_group: deploy
app_path: "/var/www/{{ project_name }}"
shared_path: "{{ app_path }}/shared"
current_path: "{{ app_path }}/current"

nginx_worker_processes: auto
nginx_worker_connections: 1024

puma_workers: 4
puma_threads_min: 5
puma_threads_max: 5
puma_port: 3000

postgresql_version: "15"
redis_version: "7.0"

log_retention_days: 30
