---
roles:
  - name: geerlingguy.security
    version: 2.2.1

  - name: geerlingguy.firewall
    version: 2.6.0

  - name: geerlingguy.nginx
    version: 3.1.4

  - name: zzet.rbenv
    version: 3.5.0

collections:
  - name: community.general
    version: ">=6.0.0"

  - name: ansible.posix
    version: ">=1.5.0"
